<?php

namespace AppBundle\Repository;

/**
 * ContestParticipantRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContestParticipantRepository extends \Doctrine\ORM\EntityRepository
{
}
