<?php

namespace AppBundle\Repository;

/**
 * PrizeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PrizeRepository extends \Doctrine\ORM\EntityRepository
{
}
