# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/service_container.html
parameters:
#    parameter_name: value

services:
     facebook_service:
          class: AppBundle\Services\FacebookService
          arguments: ['%appId%', '%appSecret%', '@service_container']
     app.event_listener.doctrine_listener:
          class: AppBundle\EventListener\DoctrineListener
          arguments: [ %kernel.root_dir%/files, "@service_container" ]
          tags:
              - { name: doctrine.event_listener, event: prePersist }
              - { name: doctrine.event_listener, event: postPersist }
              - { name: doctrine.event_listener, event: postRemove }
              - { name: doctrine.event_listener, event: preUpdate }
              - { name: doctrine.event_listener, event: postUpdate }
